name: medium

on:

  schedule: # Run workflow automatically

    - cron: '30 4 * * *'
    # - cron: '30 13 * * *'

  workflow_dispatch: # Run workflow manually (without waiting for the cron to be called), through the GitHub Actions Workflow page directly

permissions:

  contents: write # To write the generated contents to the readme

jobs:

  update-readme:

    name: Update Readme

    runs-on: ubuntu-latest

    steps:

      - name: Checkout

        uses: actions/checkout@v4

      - name: Pull in medium posts

        uses: gautamkrishnar/blog-post-workflow@1.8.7

        with:

          feed_list: "https://sagarkpanda.medium.com/feed"
          max_post_count: 10
